name: Ruff
on: [pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruff from pyproject.toml
        uses: astral-sh/ruff-action@v3
        with:
          version-file: "pyproject.toml"